### ISSUE TITLE
Embed index.html into local version

### ISSUE THREAD

**Issue by 4o3F** [InJeCTrL/BiliCLOnline#10]
GitHub Pages国内访问并不稳定，本地版本的话最好把index.html也嵌入到程序中而不是只提供API

**Comment by InJeCTrL** [comment]
感谢反馈，这个主意有道理，等空的时候我看看！

**Comment by InJeCTrL** [comment]
关联fix commits:
1006768d88bec211234a7c1e00f13adee244d0cc
bf679b8f66901ef7f68aae58b89630eeab740041
757eddda044beab6f644ce50f8593367ebbf8905
