### ISSUE TITLE
感谢作者的分享

### ISSUE THREAD

**Issue by worm128** [InJeCTrL/BiliCLOnline#12]
我本地部署了docker服务，但是访问 http://192.168.1.110:5000/ 显示验证码校验不通过，这是什么问题？HCaptchaSecret、CorsTarget、SAKeys这几个秘钥不知道有什么作用``

**Comment by InJeCTrL** [comment]
Hi 感谢支持BiliCLOnline项目！如果您要本地运行程序的话，推荐下载Release中发布的版本运行。
________________________________
From: Winlonev ***@***.***>
Sent: Saturday, August 5, 2023 4:49:10 PM
To: InJeCTrL/BiliCLOnline ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [InJeCTrL/BiliCLOnline] 感谢作者的分享 (Issue #12)


我本地部署了docker服务，但是访问 http://192.168.1.110:5000/ 显示验证码校验不通过，这是什么问题？HCaptchaSecret、CorsTarget、SAKeys这几个秘钥不知道有什么作用``

―
