### ISSUE TITLE
筛选粉丝

### ISSUE THREAD

**Issue by L1cardo** [InJeCTrL/BiliCLOnline#14]
您好，能否做到只在粉丝中抽奖？

**Comment by InJeCTrL** [comment]
您好，感谢关注BiliCLOnline项目，目前B站评论列表接口返回的数据不会包含“是否粉丝”这个属性，所以想要判断被抽中用户是否是粉丝就需要针对每条评论去做检查，我抓到这个接口可以用于获取用户与评论者之间的关系：`https://api.bilibili.com/x/space/acc/relation?mid=<member_id>`。但是针对每条评论对用户去做检查，会对B站后端产生大量请求，并且上述介绍的接口似乎在B站侧做了比较严格的流量限制，短时间大量请求很容易报错：
<img width="243" alt="图片" src="https://github.com/InJeCTrL/BiliCLOnline/assets/41737411/4573e45b-d3bc-46e3-ba53-2bd95c8f68fb">
所以我暂时不计划加入粉丝筛选的功能，如果后续有相关功能开发，会reopen这个issue。
