### ISSUE TITLE
现在有筛选水军号的功能嘛

### ISSUE THREAD

**Issue by yenora** [InJeCTrL/BiliCLOnline#2]

**Comment by InJeCTrL** [comment]
这个功能可能可以通过筛选评论内容来实现哈，请问下筛选水军号的功能您有什么建议或者想法嘛

**Comment by InJeCTrL** [comment]
可以说明一下目前通过筛选评论内容无法有效鉴别水军号的实际场景

**Comment by ErEbusE** [comment]
可能得建立名单，但这不是我们能做到的事

**Comment by yenora** [comment]
根据关注状态、B站等级和最近的动态详情进行筛选，可以提供选项来设置

**Comment by yenora** [comment]
根据关注状态、B站等级和最近的动态详情进行筛选，可以提供选项来设置

**Comment by InJeCTrL** [comment]
> 可能得建立名单，但这不是我们能做到的事

是的，建立名单的话在逻辑上可以，不过我们无法保证黑名单完全准确和它的完整性，可能采用规则进行筛选会更可行一些

**Comment by InJeCTrL** [comment]
> 根据关注状态、B站等级和最近的动态详情进行筛选，可以提供选项来设置

关注状态的话在没有用户登录凭证的状态下只能获取到部分条目，暂时想法是不给工具引入登录的选项，因为作为一个黑盒WEB平台获取B站用户登录机密对于用户来说可能不太放心

B站等级可以，由用户自定义筛掉低等级号应该可以过滤掉大部分水军号

动态详情的话需要级联地查询每个被抽中用户的动态列表再做判断，网络请求量会变大比较多，判断的依据我暂时不知道应该以什么为准，您这边对动态的判断依据有什么想法嘛

**Comment by yenora** [comment]
> > 根据关注状态、B站等级和最近的动态详情进行筛选，可以提供选项来设置
> 
> 关注状态的话在没有用户登录凭证的状态下只能获取到部分条目，暂时想法是不给工具引入登录的选项，因为作为一个黑盒WEB平台获取B站用户登录机密对于用户来说可能不太放心
> 
> B站等级可以，由用户自定义筛掉低等级号应该可以过滤掉大部分水军号
> 
> 动态详情的话需要级联地查询每个被抽中用户的动态列表再做判断，网络请求量会变大比较多，判断的依据我暂时不知道应该以什么为准，您这边对动态的判断依据有什么想法嘛

按照最近的十条动态里出现的转发抽奖动态做判断

**Comment by InJeCTrL** [comment]
> > > 根据关注状态、B站等级和最近的动态详情进行筛选，可以提供选项来设置
> > 
> > 
> > 关注状态的话在没有用户登录凭证的状态下只能获取到部分条目，暂时想法是不给工具引入登录的选项，因为作为一个黑盒WEB平台获取B站用户登录机密对于用户来说可能不太放心
> > B站等级可以，由用户自定义筛掉低等级号应该可以过滤掉大部分水军号
> > 动态详情的话需要级联地查询每个被抽中用户的动态列表再做判断，网络请求量会变大比较多，判断的依据我暂时不知道应该以什么为准，您这边对动态的判断依据有什么想法嘛
> 
> 按照最近的十条动态里出现的转发抽奖动态做判断

这样会不会比较武断，正常用户也会有这样的操作

**Comment by InJeCTrL** [comment]
目前加入了根据用户等级进行筛选的功能，可以在一定程度上作为一种筛选水军号的方式

**Comment by yenora** [comment]
> > > > 根据关注状态、B站等级和最近的动态详情进行筛选，可以提供选项来设置
> > > 
> > > 
> > > 关注状态的话在没有用户登录凭证的状态下只能获取到部分条目，暂时想法是不给工具引入登录的选项，因为作为一个黑盒WEB平台获取B站用户登录机密对于用户来说可能不太放心
> > > B站等级可以，由用户自定义筛掉低等级号应该可以过滤掉大部分水军号
> > > 动态详情的话需要级联地查询每个被抽中用户的动态列表再做判断，网络请求量会变大比较多，判断的依据我暂时不知道应该以什么为准，您这边对动态的判断依据有什么想法嘛
> > 
> > 
> > 按照最近的十条动态里出现的转发抽奖动态做判断
> 
> 这样会不会比较武断，正常用户也会有这样的操作

提供这样一个选项供用户选择

**Comment by yenora** [comment]
> 目前加入了根据用户等级进行筛选的功能，可以在一定程度上作为一种筛选水军号的方式

谢谢~
