### ISSUE TITLE
显示服务不可用

### ISSUE THREAD

**Issue by ansonlianson** [InJeCTrL/BiliCLOnline#4]
最近B站是改了某些标识参数吗，很多抽奖工具都用不了了

**Comment by InJeCTrL** [comment]
刚刚验证了下，BiliCLOnline可以抽取评论，请提供报错的场景用于分析

________________________________
发件人: ansonlianson ***@***.***>
发送时间: 2022年8月31日星期三 18:25
收件人: InJeCTrL/BiliCLOnline ***@***.***>
抄送: Subscribed ***@***.***>
主题: [InJeCTrL/BiliCLOnline] 显示服务不可用 (Issue #4)


最近B站是改了某些标识参数吗，很多抽奖工具都用不了了

―
